# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netuno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='senha',
        ),
    ]
